### ISSUE TITLE
Oomph stops sending OSC data when FX window is closed in Reaper

### ISSUE THREAD

**Issue by AndrewRahman** [DanielRudrich/OomphSC#3]
When not visible on the screen the plugins stop sending data.
At least this occurred between Reaper and TouchDesigner in our tests, if the FX window in Reaper was closed TouchDesigner would no longer receive any data. Once the FX window was opened and Oomph was on the screen, then TouchDesigner would receive the data.

**Comment by DanielRudrich** [comment]
Oh yes, I put the sending logic into the editor... not a good choice :D
