### ISSUE TITLE
Feature Request: Could be cool to also have stereo

### ISSUE THREAD

**Issue by AndrewRahman** [DanielRudrich/OomphSC#6]
I see that the plugin sums both channels to mono, and I think with ambisonics this works in most cases, however we've seen from working with artists that the majority of the time the artists are taking an existing stereo track that they've made and therefore there are a lot of Stereo encoders in use, and the use case here is often that the stereo sound has two very different sounds or ping pong delay effects occurring in the two different channels. With the Oomph summing to mono we can't have two different events happening occurring at the two different locations in the visuals. I think it might make sense to do like Waves here and make two separate plugins, one mono and one stereo so the artists can choose what type of data they want to send and when.

**Comment by DanielRudrich** [comment]
That's definitely on my list I want to implement! 

I think I'll will go with a switch mono <-> stereo within the plug-in. If stereo, signals get analyzed separately, visualized with split bars, and an additional value will be sent  via OSC.
